language: generic
deploy:
  provider: pypi
  user: "__token__"
  password:
    secure: "luC7lTzGlykir8El5VRZ4ovnSoK48wGGu/AqpB7IqYt6G2sWn8r01LlXo2EwMu/OGCXEyu2X3fEM8ACoXl0t7K8SDNnKirImrXmoxxL/QrIIXzGPun6FyGpigeY7oUvIkNH1VSaulHWZ+pIQ4YMV/NmzYXdtKI4F4EqGRyRC0/PKoh2ohX1AuCDSGPa3YbbMVwMmScoxpYJMhhB1TBHDdAfR5QFdZ5YhJXr0VhIEKcOopIzTpff7Qn8WQ5tnjaTPFJx5P7Mbbi3+Lz+9/bNgU7rCiMoXahO49aG0nhc+rSGOdjxFy+EgfA0lcBzwW6CSQpSTp5eDWqYlOBNWNBmgFuHetjLYm81zkTutO6yUb+UJjIOoyLf4ImkGWC3v4dC+CIqDzhnhUVRaXEnkqENKqk+iGQGdj4g+eHEVtG0IgPbSPDEiypdODds4fQFhw54OvPbf7X8tHACeybgYS+TLjC+Rk303c4yGhBvmDkFFJS6y7MHpMK8PZ5icpyLYq7VaKTkUiD8l3GhFIryseO0djNeByZ3vX/ClwunAZsC4cM56JrP5JzWR44xK4uD+JHSn+/ft8muMJsoOu7SKKIj0Jm2aBZCxsjQ5Az3j20LOGZ2iuzZJjWMaGlDBN8aiA8+ZUEE9FLHyAWfZutot7K/r43H7kgULv+7HhWcRFPYQdg0="
