language: generic
deploy:
  provider: pypi
  user: "iamsinghrajat"
  password: "pypi-AgEIcHlwaS5vcmcCJGU0YTM4ZDhhLTJjYjktNDRiNi1iMjJhLWE1OWU4OGJiODEwYwACJXsicGVybWlzc2lvbnMiOiAidXNlciIsICJ2ZXJzaW9uIjogMX0AAAYg4k4cAKisQcfVyq7tVD-abFVZjWM4l8qC8W4ayIX6mIE"
  skip_cleanup: true
  skip_existing: true