language: generic
deploy:
  provider: pypi
  user: "iamsinghrajat"
  password:
    secure: "Z7n45LuFkb319qiDqi1ACFVPDLBT2NaO/tJbDSGNpMuXYFE9u5yhGUgpfHdH2dh1ZtgB6zCPBdNzYuSm+f9nm29fgNmm1/kgVWRK1ZX3vONASgrXTevnzLxoFhPJ9CXpOYFgm7WE+TIrFT6eL0bt1cAy4e+EggP0hO5ai0ccuPJifjU6F6uu3DcDHGPsH5DbFx0oqyhvyUZ/Yb3nPSGuHfpZ9mI1Z7/RQvSwBmeZQ8hmZW8U2AoKsjzToOoRTD/MsAx7MLxjdL56vjGp7NlYhVM8VFuS3Ff/5Tf8cYPd+5ffIZBfYYFOvxS0ghEDNBue15POffkN9HiAquyHJ1lLIcSoFTF+dD1/oUtvnmxb+0Kj6oADF+8dSiwaeAwacQ6sm/A/3ZdMk4+KrPlX9LFuUSRBxm0cM/q6Hewfk0faNU4b7FQ4rhX6URPiNTzEs4lmLewGPykcTpbNglkaobmcBl2R8kHJufIcHabvGPkBjpUo9m2kI1r10kEhInDm2MDpAK/AolEA7gcQQH5B22bPxCTyuqve0QJr2b+oFM+c7iaFWyD3Gsh/YnE5nqllBIflUYgltpInkIcd9oNiht7t8tmCvqo+rjlzVmq/qgGKyecNyNtMzcj1vGwqIGanBKPNAcOR+oW2XqQvzO4c0LNwFxZDpoB1U5d4oRS01BCfGUY="
  skip_cleanup: true
  skip_existing: true