language: generic
deploy:
  provider: pypi
  user: "iamsinghrajat"
  password:
    secure: "TRMSDRbPNQoXi+pybbGUlQ/95VTKJN9a6AlmrpEAKwDvQcXYUnCLrTQ0T9/7L/lkPcQXR4kmnkN4Qjh90v+9wG8M1ir8iVMkIywme+GUJ61JbQYQwBJ9eOd1157OdjrXPqUzh/ymKUHCSPdw2zEU9U0a05ozbW8kPG2GdXqO4RZHzUs7V/Be3bniNbRSYzi1Eve5Aa7dcPYFISO7ao0Fl9V9PqrZYL0RLPfV6M87d6O5DYfy5pZv5QdnYaIYuX/QTyboXarp3qhv+irwWv74ahn7uGaM0ZqM7VsomAqSqNlZgieRqDT3TPOAOYN9rHeFnxIC3KyLdQUqS8Djq7/DSHAyA5ie4yydfHbYrCJptUG92lX5vGMzT/UliYgGQJLi5r8Y1aj4llqmMLdjAsTk8M2l5Xb4IdsGOG6WCY12OSvlvK4gOTIdC0Nv3RLWjuJYkcYTg4rMYQnNSq7LGpZyeks2je2NvUamK7Z2v6w2O4igEt0vXD4MN26P95lG7vb/RYgqn91/GPA3dYAS78AQ3JYsKvG1W0QrvfXQ+X6kXurzDm8+LYfv28Q6c4XM5LKGLPvzyN+I1R4OHXX5q284aO4V53wHeWI1XAYC6ehnjCbGU0bj2whiGZ/nceWYxmVl1byP8Hg6Li2iDqTT1CiPykQfOC8m7uxKktcQ3QMJZZs="
  skip_cleanup: true
  skip_existing: true