language: generic
deploy:
  provider: pypi
  user: "__token__"
  password:
    secure: "sXP+tlDtrJIidCaACHlBkjNicAM6ODugRzYQzee9r054wWtDUOoF4eMwDRej4Kw35NAQZCh4Z2NmqAPS2yAeTJQqjr6bpZ5s2wW87bcU0dDcYDJnDI/510+rXifMUYq+3LKaPQgsoFQi91AtWalMqhptXg6VRUkaG44ee3WAOo9zjBRGW2Pl+nVRZMwvlg1RYlMqZnaCsOEhqsgb7hG564Um858vAR6s/NzexnULyWkzCPTrcm39xs+8RxAlY+8nDymCUWpxh1cI6Wrs7dvUYT/0lAqbD4Wb8NhNzA5dNLhriVw+E8K5GD5v0z+ORzQlqa5/H9S7XfJ5mvQy5ZLltw31cas9T1rMDJRT8Pnl16NgqKJNVhGVoF6ZCSySY6tegFwDzvPXv1u/L4vzO0vycPOlA0CQRvgsyDodLVvd+hRXQpO3yEdRa+76u8nyYKexxY59fwXPFk65VrLaknfHxM1MR/zWSfA1Mg2vZjdqxKkhUmmvAaBMuPGA+ksvhmclvF3ZvG5vVtYrGV/813EhRpPFSjThiAISByl2F+bdE++jahcQfP9vlSR1FF4o9HeRaP0YOH9aC9Mg0kujGxYgJrvNZ8WbJuspPJLJUxgj0uo/Qr3PXXCx9waqRhSKDdRIzD+NGA28ghdPYDWSLyLu+qnRCZHNPPNVIS3abBw4I2E="
  skip_cleanup: true
  skip_existing: true